version: '3.9'

services:
  php:
    platform: linux/amd64         
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html/api
    depends_on:
      - db

  db:
    platform: linux/amd64         
    image: mysql:8                
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: monks_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    command: --innodb-use-native-aio=0q
    volumes:
      - monks_mysql_data:/var/lib/mysql   
      - ./mysql-init:/docker-entrypoint-initdb.d

volumes:
  monks_mysql_data:
